apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pipeline-config
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
  pipeline_config.yaml: |-
    {{ .Values.pipelineConfig | toYaml | nindent 4 }}
